### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by rnkhouse** [bitnami/bitnami-docker-phpmyadmin#21]
**Description**

Currently there is no option to provide SSL while connecting with phpmyadmin. https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_ssl

**Describe the results you received:**

There is no way to provide SSL in connection which is insecure.

**Describe the results you expected:**

There should be an option to connect database with SSL.

**Additional information you deem important (e.g. issue happens only occasionally):**

Helm chart is using your image and they suggested me to open an issue here. Please take a look at this thread.
https://github.com/helm/charts/issues/9662

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.0-ce-beta1
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        78a6bdb
 Built:             Thu Sep  6 22:42:13 2018
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0-ce-beta1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       78a6bdb
  Built:            Thu Sep  6 22:49:35 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 95
 Running: 0
 Paused: 0
 Stopped: 95
Images: 466
Server Version: 18.09.0-ce-beta1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: jznr1pf3qlt5i2c16rfjpc5zs
 Is Manager: true
 ClusterID: iq5dgbqbyc1bmpru3xk6od4zf
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d63011e
ID: CZHV:AGN7:QLO2:XR47:KVKD:2QRK:MUQG:R5GQ:VHHP:E7MH:3OKR:FNGT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 159
 System Time: 2019-01-03T16:13:30.3444266Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by andresbono** [comment]
Hi @rnkhouse, thanks for submitting this issue.

We are going to evaluate and implement (if possible) the addition of this feature.

**Comment by rnkhouse** [comment]
@andresbono Hi. Is there any update on this?

**Comment by marcosbc** [comment]
Hi @rnkhouse, we have an internal task for working on this issue this week, so if everything goes fine it should be released by end of week or the next one.

**Comment by rnkhouse** [comment]
@marcosbc @carrodher When do you think this issue will resolve?

**Comment by marcosbc** [comment]
Hi @rnkhouse, thanks for updating this case. In the end we were not able to finish it by the time we suggested.

However, I had a free slot today and could start working at it. We were successfully able to implement and test it, and are working on getting the containers released, so it should be available later today with the SSL options (which will appear in the README).

Keep an eye and let us know if this works for you!

**Comment by rnkhouse** [comment]
Thanks @marcosbc for quick reply and fix!  👍
