### ISSUE TITLE
 Hope to increase SESSION TIMEOUT control

### ISSUE THREAD

**Issue by xxstop** [bitnami/bitnami-docker-phpmyadmin#23]
Hi, 
Hope to increase SESSION TIMEOUT control.

Thank.

**Comment by carrodher** [comment]
Hi, I don't fully understand your request, please, can you elaborate a bit more what is your goal and your use case? Thanks

**Comment by xxstop** [comment]
Can a constant be added to control the time setting of php's gc_maxlifetime and phpmymadin's LoginCookieValidity?


I work:
```Dockerfile
FROM bitnami/phpmyadmin:5.0.2-debian-10-r127

RUN echo "\$cfg['LoginCookieValidity'] = 172800;" >> /opt/bitnami/phpmyadmin/config.inc.php
RUN sed -i 's/session.gc_maxlifetime = 1440/session.gc_maxlifetime = 172800/' /opt/bitnami/php/etc/php.ini
```

**Comment by juan131** [comment]
Hi @xxstop 

I am afraid that we don't support to customize that setting as we do for other ones. For instance, you can use **PHP_UPLOAD_MAX_FILESIZE**, **PHP_POST_MAX_SIZE** and **PHP_MEMORY_LIMIT** as it's explained [here](https://github.com/bitnami/bitnami-docker-phpmyadmin#environment-variables) to modify some PHP settings, but we don't have one for the session timeout.

You can customize and create your own image based on this one as it's explained [here](https://github.com/bitnami/bitnami-docker-phpmyadmin#extend-this-image) adding any other customization in the php.ini file.

**Comment by xxstop** [comment]
Okay, thank you
