### ISSUE TITLE
Env var PHP_MAX_INPUT_VARS not working

### ISSUE THREAD

**Issue by GuillaumeOuint** [bitnami/bitnami-docker-phpmyadmin#25]
Hello,

I'm using the image `phpmyadmin:5.0.3-debian-10-r3` with the env var `PHP_MAX_INPUT_VARS` but it's not working at all (I mean that the php max_input_vars is not modified by setting this variable)

**Steps to reproduce the issue:**

1. Deploy the container
2. Try to export a big DB
3. PHP Warnings/Errors

**Describe the results you received:**
```
Errors:
PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0
```
AND
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to PhpMyAdmin\\Export::exportDatabase() must be of the type string, null given, called in /opt/bitnami/phpmyadmin/export.php on line 526 and defined in /opt/bitnami/phpmyadmin/libraries/classes/Export.php:646\nStack trace:\n#0 /opt/bitnami/phpmyadmin/export.php(526): PhpMyAdmin\\Export->exportDatabase()\n#1 {main}\n  thrown in /opt/bitnami/phpmyadmin/libraries/classes/Export.php on line 646
```

**Describe the results you expected:**

No error and the .sql file of the export to be populated with the database

**Additional information you deem important (e.g. issue happens only occasionally):**

Using on Kubernetes. Error only on big database

**Version**

- Output of `docker version`:

```
Can't get because i'm on k8s
```

- Output of `docker info`:

```
Can't get because i'm on k8s
```

- Output of `docker-compose version` (if applicable):

```
Can't get because i'm on k8s
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running on Kubernetes.

**Comment by GuillaumeOuint** [comment]
Same behavior with the docker tag 5.0.3

**Comment by GuillaumeOuint** [comment]
This env var is not settings the max_input_vars to it's value but the max_input_time instead. (Verified on the phpinfo)

**Comment by GuillaumeOuint** [comment]
And so, the PHP_MAX_INPUT_TIME is not used/useless because the env variable taken is not INPUT_TIME but INPUT_VARS for max_input_time.
How could this has been pushed in build/prod ?

**Comment by GuillaumeOuint** [comment]
File to modify: 5/debian-10/rootfs/opt/bitnami/scripts/libphp.sh
Line 61 is
`! is_empty_value "$PHP_MAX_INPUT_VARS" && info "Setting PHP max_input_vars option" && php_conf_set max_input_time "$PHP_MAX_INPUT_VARS"`

And should be:
`! is_empty_value "$PHP_MAX_INPUT_VARS" && info "Setting PHP max_input_vars option" && php_conf_set max_input_vars "$PHP_MAX_INPUT_VARS"`

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue, we are aware of the typo and we are working on releasing a new version of the affected containers. As you rightly said, the issue is related to

https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/fd55781a816438a74cdaea19a8532cd0008f8a21/5/debian-10/rootfs/opt/bitnami/scripts/libphp.sh#L61

I just reviewed your PR and it looks good to me, once merged in GitHub, we need to work on a release on our side to push a new image to the container registries so it can take some time, but we're working on it. Thanks
