### ISSUE TITLE
Additional environment variables

### ISSUE THREAD

**Issue by rechandler12** [bitnami/bitnami-docker-phpmyadmin#27]
Hello,
could you implement extra environment variables? Just like we have in original Docker project: https://github.com/phpmyadmin/docker  

Particularly these ones: 
- PMA_CONTROLUSER
- PMA_CONTROLPASS
- PMA_PMADB
- PMA_USER_CONFIG_BASE64

Not all of the above variables are mentioned in original documentation as possible to use. I assure you they are supported - I used them and you can find a list here: https://github.com/phpmyadmin/docker/blob/master/config.inc.php

**Comment by marcosbc** [comment]
Hi @rechandler12, thanks for the feedback. 

I've opened a task in our backlog to check this. Note that we're currently a small team so it's unlikely we'll be able to spend any time on this soon.

We're always open for PRs, so if you're up to it, feel free to contribute! We'd be glad to check it. You can locate the initialization logic in the [`rootfs` directory](https://github.com/bitnami/bitnami-docker-phpmyadmin/tree/master/5/debian-10/rootfs) of this repo.

**Comment by tebaly** [comment]
Append

https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/1422e193ef0faeb9c10ee650dcf305b6a82f669d/5/debian-10/rootfs/opt/bitnami/scripts/phpmyadmin-env.sh#L71

```
export UPLOAD_LIMIT="${UPLOAD_LIMIT:-}"
export MEMORY_LIMIT="${MEMORY_LIMIT:-}"
export MAX_EXECUTION_TIME="${MAX_EXECUTION_TIME:-}"

```
# Environment variables summary
https://hub.docker.com/r/phpmyadmin/phpmyadmin/

For Example
https://gitlab.com/tebaly/phpmyadmin/-/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/phpmyadmin-env.sh#L76

**Comment by tebaly** [comment]
Oh no... You seem to be ignoring the sources :(

https://github.com/phpmyadmin/docker/blob/master/apache/config.inc.php

**Comment by carrodher** [comment]
Unfortunately, the task is still on the backlog, in the same way, please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpmyadmin#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
