### ISSUE TITLE
server-status not found

### ISSUE THREAD

**Issue by rechandler12** [bitnami/bitnami-docker-phpmyadmin#28]
**Description**

I’m trying to start metrics for helm chart. Unfortunately the 404 problem have been showing up and I think it’s because of the lack of code.

specifically this one:
```
  <Location /server-status>
    Require local
    SetHandler server-status
  </Location>
```

in this [file](https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/apache/bitnami-templates/app-http-vhost.conf.tpl)

You can see this [file](https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/apache/bitnami-templates/bitnami.conf.tpl) contains this code. 

So it’s seems the problem concerns other applications based on Apache and also https configuration.

**Steps to reproduce the issue:**

1. Install chart:
```
helm install -f values.yaml phpmyadmin bitnami/phpmyadmin --version 7.0.1
```
with values.yaml
```
metrics:
  enabled: true
```
2. check metrics container logs
3. see error

**Describe the results you received:**

Get 404 from Apache

**Describe the results you expected:**

See server-status

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
It's related with: https://github.com/bitnami/charts/issues/4581

**Comment by marcosbc** [comment]
Hi @rechandler12, you are right. When we migrated the initialization logic to be based on Bash scripts (available in the `rootfs` folder) it seems we did not properly test this specific scenario.

We're going to work on adding this back. Once the changes are merged, you should expect to see the file `/opt/bitnami/apache/conf/vhosts/00_status-vhost.conf` with these contents:

```
<VirtualHost 127.0.0.1:8080>
  ServerName status.localhost
  <Location /server-status>
    Require local
    SetHandler server-status
  </Location>
</VirtualHost>
```

And the Apache server status page should be accessible via http://status.localhost:8080/server-status

**Comment by marcosbc** [comment]
@rechandler12 We have implemented this in [`5.0.4-debian-10-r51`](https://github.com/bitnami/bitnami-docker-phpmyadmin/commit/6070d3a8fb022a54b73d6902a8563eeb3186b88d). Let us know if you find any issues.

**Comment by rechandler12** [comment]
It is working now as expected, thanks

**Comment by marcosbc** [comment]
Thanks! I'll close this issue but if you find any issues feel free to comment here or open a new one.
