### ISSUE TITLE
PMA_ABSOLUTE_URI not supported

### ISSUE THREAD

**Issue by codematters-pl** [bitnami/bitnami-docker-phpmyadmin#29]
Hello,

I tried to deploy bitnami phpmyadmin chart with image built from this repository, but it seems that PMA_ABSOLUTE_URI variable is missing in config.inc.php

I'm not able to deploy site under prefix e.g. /admin/pma because after succesful login it redirects to /index.php

Is there a chance to get support for PMA_ABSOLUTE_URI variable? 

Thank you in advance 👍

**Comment by marcosbc** [comment]
Hi @creabsoft, thanks for the feedback. This is not currently something supported by the container but could make sense for certain scenarios, like the one you mention.

In #27 there was a request to add some environment variables, for which we opened an internal task. I've updated the tag to include this envvar.

Note that we're currently a small team, and considering we have lots of things in our plate it's unlikely we'll be able to spend any time on this soon.

However, if you feel confident and want to speed up the process, we're accepting external contributions that help improve these images. If you're up for it, feel free to send a PR, we'll be glad to review and help with the release process. You can locate the initialization logic in the [`rootfs` directory](https://github.com/bitnami/bitnami-docker-phpmyadmin/tree/master/5/debian-10/rootfs) of this repo.

**Comment by larryzhu2018** [comment]
please review PR: https://github.com/bitnami/bitnami-docker-phpmyadmin/pull/30/files

**Comment by marcosbc** [comment]
Will do, thanks!
