### ISSUE TITLE
Size of a request header field exceeds server limit.

### ISSUE THREAD

**Issue by muhammad-naderi** [bitnami/bitnami-docker-phpmyadmin#36]
After docker-compose up, opening in a default browser will result into following error

`Bad Request`
`Your browser sent a request that this server could not understand.`
`Size of a request header field exceeds server limit.`

however browsing in incognito browser seems to work fine.
could you increase the default header size ?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpmyadmin#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
